name: GatherUs API deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore ./GatherUs.API/GatherUs.API.csproj

      - name: Build
        run: dotnet build ./GatherUs.API/GatherUs.API.csproj --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/gatherusapi:${{ github.sha }} ./GatherUs.API
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/gatherusapi:${{ github.sha }}

