name: GatherUs API deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push container image to registry
      uses: azure/container-apps-deploy-action@v2
      with:
        appSourcePath: ${{ github.workspace }} 
        registryUrl: docker.io
        registryUsername: ${{ secrets.REGISTRY_USERNAME }}
        registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
        imageToBuild: docker.io/oleksandrbob/gather-us:${{ github.sha }}